# Generated by Django 5.2.3 on 2025-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prenda',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prenda',
            name='estatus',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('apartado', 'Apartado'), ('en_uso', 'En Uso'), ('dañado', 'Dañado'), ('mantenimiento', 'En Mantenimiento'), ('lavanderia', 'En Lavandería')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='prenda',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='prenda',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lugar o sitio del traje'),
        ),
        migrations.AddField(
            model_name='prenda',
            name='tallas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
