# Generated by Django 5.2.3 on 2025-01-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_prenda_cantidad_prenda_color_prenda_estatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrendaVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estatus', models.CharField(choices=[('disponible', 'Disponible'), ('apartado', 'Apartado'), ('en_uso', 'En Uso'), ('dañado', 'Dañado'), ('mantenimiento', 'En Mantenimiento'), ('lavanderia', 'En Lavandería')], default='disponible', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='variantes/')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.prenda')),
            ],
            options={
                'unique_together': {('prenda', 'color', 'talla')},
            },
        ),
    ]