# Generated by Django 5.2.3 on 2025-08-25 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_prendavariante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrendaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=20, unique=True)),
                ('estatus', models.CharField(choices=[('disponible', 'Disponible'), ('apartado', 'Apartado'), ('en_uso', 'En Uso'), ('dañado', 'Dañado'), ('mantenimiento', 'En Mantenimiento'), ('lavanderia', 'En Lavandería')], default='disponible', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la unidad')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='inventario.prendavariante')),
            ],
            options={
                'verbose_name': 'Unidad de Prenda',
                'verbose_name_plural': 'Unidades de Prenda',
                'ordering': ['numero_serie'],
            },
        ),
    ]
