# Generated by Django 5.2.1 on 2025-09-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
