# Generated by Django 5.2.3 on 2025-09-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prendavariante',
            name='estatus',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('apartado', 'Apartado'), ('en_uso', 'En Uso'), ('dañado', 'Dañado'), ('mantenimiento', 'En Mantenimiento'), ('lavanderia', 'En Lavandería')], max_length=20),
        ),
    ]
