# Generated by Django 5.2.3 on 2025-09-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentas', to='inventario.cliente')),
                ('prendas', models.ManyToManyField(related_name='rentas', to='inventario.prendaunidad')),
            ],
            options={
                'verbose_name': 'Renta',
                'verbose_name_plural': 'Rentas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
