# Generated by Django 5.2.3 on 2025-09-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0003_migrate_cliente_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
