# Generated by Django 5.2.1 on 2025-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0004_renta_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pendiente_devolucion', 'Pendiente de Devolución'), ('finalizada', 'Finalizada')], default='activa', max_length=20),
        ),
    ]
