# Generated by Django 5.2.1 on 2025-09-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0005_alter_renta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='ine_entregada',
            field=models.BooleanField(default=False, verbose_name='INE entregada'),
        ),
    ]
