# Generated by Django 5.2.1 on 2025-09-26 06:05

from django.db import migrations

def fix_ine_entregada(apps, schema_editor):
    Renta = apps.get_model('rentas', 'Renta')
    # Asegurar que todas las rentas tengan ine_entregada = False por defecto
    Renta.objects.filter(ine_entregada__isnull=True).update(ine_entregada=False)

def reverse_fix_ine_entregada(apps, schema_editor):
    pass  # No hacer nada en reversa

class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0006_renta_ine_entregada'),
    ]

    operations = [
        migrations.RunPython(fix_ine_entregada, reverse_fix_ine_entregada),
    ]
