# Generated by Django 5.2.1 on 2025-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0007_auto_20250926_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='ine_entregada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='INE entregada'),
        ),
    ]
