# Generated by Django 5.2.1 on 2025-09-26 06:23

from django.db import migrations

def recalcular_precios_rentas(apps, schema_editor):
    Renta = apps.get_model('rentas', 'Renta')
    for renta in Renta.objects.all():
        # Calcular precio base
        total = 0
        for prenda in renta.prendas.all():
            total += prenda.variante.prenda.precio
        
        # Aplicar recargo si no hay INE
        if not renta.ine_entregada:
            from decimal import Decimal
            total = total * Decimal('1.10')
        
        # Actualizar precio
        renta.precio_total = total
        renta.save()

def reverse_recalcular_precios(apps, schema_editor):
    pass  # No hacer nada en reversa

class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0008_alter_renta_ine_entregada'),
    ]

    operations = [
        migrations.RunPython(recalcular_precios_rentas, reverse_recalcular_precios),
    ]
