# Generated by Django 5.2.1 on 2025-12-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0009_auto_20250926_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='anticipo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Anticipo pagado'),
        ),
    ]
