# Generated by Django 5.2.1 on 2025-12-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0010_renta_anticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='cargo_retraso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cargo por retraso'),
        ),
    ]
